[package]
name = "project-one"
version = "0.1.0"
edition = "2018"

[dependencies]
support     = { path = "../../support" }
environment = { path = "../../environment" }
gavle       = { path = "../../gavle" }
log         = "0.4"
winit       = "0.25"
bytemuck    = "1"
rayon       = "1"
